package com.mahdihi69.dastansaz;

import android.Manifest;
import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class StoryActivity extends Activity {
    LinearLayout root, content; TextView status, result; EditText topic, lesson, ending, hero;
    Spinner genre, age, length; TextToSpeech tts; SpeechRecognizer recognizer; ExecutorService io=Executors.newSingleThreadExecutor();
    ArrayList<String> saved=new ArrayList<>();
    final int MIC=44;
    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(39,25,71)); loadSaved(); build(); initTts();}
    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
    TextView tv(String s,int size,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(18,12,18,12);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(bg(Color.rgb(100,65,170),30));b.setPadding(12,4,12,4);return b;}
    EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setTextColor(Color.DKGRAY);e.setHintTextColor(Color.GRAY);e.setGravity(Gravity.RIGHT);e.setSingleLine(false);e.setPadding(18,10,18,10);e.setBackground(bg(Color.rgb(247,244,251),24));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,58);p.setMargins(0,7,0,7);e.setLayoutParams(p);return e;}
    Spinner spin(String[] a){Spinner s=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a);s.setAdapter(ad);s.setBackground(bg(Color.rgb(247,244,251),24));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,58);p.setMargins(0,5,0,5);s.setLayoutParams(p);return s;}
    void build(){
        ScrollView scroll=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,14,18,24);root.setBackgroundColor(Color.rgb(250,248,253));scroll.addView(root);setContentView(scroll);
        TextView head=tv("📖 داستان‌ساز",27,Color.WHITE);head.setGravity(Gravity.CENTER);head.setTypeface(null,1);head.setBackground(bg(Color.rgb(62,39,104),36));head.setPadding(10,20,10,20);root.addView(head,new LinearLayout.LayoutParams(-1,82));
        TextView sub=tv("داستان، شعر و قصه صوتی با کمک هوش مصنوعی",14,Color.rgb(80,70,95));sub.setGravity(Gravity.CENTER);root.addView(sub);
        LinearLayout tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setGravity(Gravity.CENTER);Button story=btn("📖 داستان");Button poem=btn("🎵 شعر");Button library=btn("📚 کتابخانه");tabs.addView(story,new LinearLayout.LayoutParams(0,58,1));tabs.addView(poem,new LinearLayout.LayoutParams(0,58,1));tabs.addView(library,new LinearLayout.LayoutParams(0,58,1));root.addView(tabs);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content);
        showStory(); story.setOnClickListener(v->showStory());poem.setOnClickListener(v->showPoem());library.setOnClickListener(v->showLibrary());
    }
    void clear(){content.removeAllViews();}
    void label(String s){content.addView(tv(s,14,Color.rgb(74,57,91)));}
    void showStory(){clear();label("موضوع داستان");topic=field("مثلاً: پسری که از تاریکی می‌ترسید");content.addView(topic);label("نوع داستان");genre=spin(new String[]{"ماجراجویی","کودکانه","فانتزی","طنز","رازآلود","علمی‌تخیلی","خانوادگی","احساسی","آموزشی"});content.addView(genre);label("رده سنی");age=spin(new String[]{"کودک ۴ تا ۷ سال","کودک ۸ تا ۱۲ سال","نوجوان","جوان","بزرگسال","همه سنین"});content.addView(age);label("مدت داستان");length=spin(new String[]{"کوتاه (۲ تا ۳ دقیقه)","متوسط (۵ تا ۷ دقیقه)","بلند (۱۰ تا ۱۵ دقیقه)"});content.addView(length);label("پند یا آموزش");lesson=field("مثلاً: شجاعت و اعتمادبه‌نفس");content.addView(lesson);label("نتیجه‌ای که می‌خواهی");ending=field("مثلاً: قهرمان بفهمد ترس طبیعی است اما نباید جلوی او را بگیرد");content.addView(ending);label("نام شخصیت اصلی (اختیاری)");hero=field("مثلاً: آرش، باران، نیما...");content.addView(hero);
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button voice=btn("🎙️ گفتن موضوع");Button make=btn("✨ ساخت داستان");actions.addView(voice,new LinearLayout.LayoutParams(0,62,1));actions.addView(make,new LinearLayout.LayoutParams(0,62,1));content.addView(actions);status=tv("آماده‌ام...",13,Color.GRAY);status.setGravity(Gravity.CENTER);content.addView(status);result=tv("",17,Color.rgb(45,35,55));result.setPadding(10,20,10,20);content.addView(result);voice.setOnClickListener(v->listen(topic));make.setOnClickListener(v->generate(false));}
    void showPoem(){clear();label("موضوع شعر");topic=field("مثلاً: مادر، باران، دوستی...");content.addView(topic);label("سبک");genre=spin(new String[]{"احساسی","کودکانه","عاشقانه","طنز","حماسی","معنوی","ترانه","کوتاه و ساده"});content.addView(genre);label("قافیه");age=spin(new String[]{"آزاد","قافیه‌دار","غزل‌گونه","چهارپاره"});content.addView(age);label("نام یا واژه خاص");hero=field("مثلاً: مریم");content.addView(hero);Button make=btn("🎵 شعرم را بساز");content.addView(make);status=tv("آماده‌ام...",13,Color.GRAY);status.setGravity(Gravity.CENTER);content.addView(status);result=tv("",17,Color.rgb(45,35,55));result.setPadding(10,20,10,20);content.addView(result);make.setOnClickListener(v->generate(true));}
    void showLibrary(){clear();label("📚 داستان‌های ذخیره‌شده");SharedPreferences p=getSharedPreferences("stories",0);String all=p.getString("all","");if(all.isEmpty()){TextView e=tv("هنوز داستانی ذخیره نکرده‌ای.",16,Color.GRAY);e.setGravity(Gravity.CENTER);content.addView(e);return;}for(String s:all.split("\\n\\n---\\n\\n")){TextView x=tv(s,16,Color.DKGRAY);x.setBackground(bg(Color.WHITE,24));content.addView(x);Button play=btn("🔊 خواندن");content.addView(play);play.setOnClickListener(v->speak(s));}}
    String key(){String k=BuildConfig.GEMINI_API_KEY;return k==null?"":k.trim();}
    void generate(boolean poetry){String t=topic.getText().toString().trim();if(t.isEmpty()){toast("موضوع را وارد کن");return;}status.setText("🧠 در حال آفرینش... داستان دارد شکل می‌گیرد");String prompt;if(poetry){prompt="یک شعر فارسی زیبا و اصیل درباره موضوع «"+t+"» بساز. سبک: "+genre.getSelectedItem()+". قالب: "+age.getSelectedItem()+". واژه/نام ویژه: "+hero.getText()+". شعر روان و قابل خواندن با صدای بلند باشد. فقط خود شعر را بده.";}else{prompt="یک داستان فارسی کاملاً تازه و جذاب بساز. موضوع: "+t+". ژانر: "+genre.getSelectedItem()+". رده سنی: "+age.getSelectedItem()+". مدت: "+length.getSelectedItem()+". پند/آموزش: "+lesson.getText()+". نتیجه: "+ending.getText()+". شخصیت اصلی: "+hero.getText()+". شروع گیرا، شخصیت‌پردازی، اوج، پایان رضایت‌بخش و پیام طبیعی داشته باشد. از کلیشه‌های تکراری دوری کن. فقط متن اثر را بده.";}String k=key();if(k.isEmpty()){showText(poetry?"برای شعر نمونه: باران که آمد، کوچه پر از خاطره شد...\\n\\nبرای تولید واقعی، کلید Gemini را در Secrets با نام GEMINI_API_KEY قرار بده.":"نمونه داستان آماده است.\\n\\nبرای تولید واقعی، کلید Gemini را در Secrets با نام GEMINI_API_KEY قرار بده.");return;}io.execute(()->{try{URL u=new URL("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+URLEncoder.encode(k,"UTF-8"));HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setConnectTimeout(20000);c.setReadTimeout(60000);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);JSONObject body=new JSONObject();JSONArray contents=new JSONArray();JSONObject cc=new JSONObject();JSONArray parts=new JSONArray();parts.put(new JSONObject().put("text",prompt));cc.put("parts",parts);contents.put(cc);body.put("contents",contents);OutputStream os=c.getOutputStream();os.write(body.toString().getBytes(StandardCharsets.UTF_8));os.close();InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);br.close();if(c.getResponseCode()>=400)throw new Exception("HTTP "+c.getResponseCode());String text=new JSONObject(sb.toString()).getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts").getJSONObject(0).getString("text");runOnUiThread(()->showText(text.trim()));}catch(Exception e){runOnUiThread(()->{status.setText("⚠️ خطا در ساخت؛ دوباره امتحان کن");toast(e.getMessage()==null?"خطای ارتباط":e.getMessage());});}});}
    void showText(String s){result.setText(s);status.setText("✨ آماده شد");LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);Button speak=btn("🔊 خواندن");Button save=btn("💾 ذخیره");Button again=btn("🔄 دوباره");bar.addView(speak,new LinearLayout.LayoutParams(0,60,1));bar.addView(save,new LinearLayout.LayoutParams(0,60,1));bar.addView(again,new LinearLayout.LayoutParams(0,60,1));content.addView(bar);speak.setOnClickListener(v->speak(s));save.setOnClickListener(v->save(s));again.setOnClickListener(v->showStory());}
    void save(String s){SharedPreferences p=getSharedPreferences("stories",0);String old=p.getString("all","");String n=old.isEmpty()?s:old+"\n\n---\n\n"+s;p.edit().putString("all",n).apply();toast("💾 ذخیره شد");}
    void initTts(){tts=new TextToSpeech(this,r->{if(r==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("fa","IR"));tts.setSpeechRate(.9f);}});}
    void speak(String s){if(tts!=null){tts.stop();tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"story");}}
    void listen(EditText target){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("تشخیص گفتار روی گوشی در دسترس نیست");return;}if(recognizer!=null)recognizer.destroy();recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(new android.speech.RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("صدای شما دریافت نشد");}public void onResults(Bundle b){ArrayList<String> x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty())target.setText(x.get(0));}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);recognizer.startListening(i);status.setText("🎙️ دارم گوش می‌دهم...");}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    void loadSaved(){}
    @Override protected void onDestroy(){if(tts!=null)tts.shutdown();if(recognizer!=null)recognizer.destroy();io.shutdownNow();super.onDestroy();}
}
