package com.mahdihi69.dastansaz;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class StoryActivity extends Activity {
    LinearLayout root,content; TextView status,result; EditText topic,lesson,ending,hero; Spinner genre,age,length; TextToSpeech tts; SpeechRecognizer recognizer; QwenTts qwen; ExecutorService io=Executors.newSingleThreadExecutor(); final int MIC=44;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(39,25,71));qwen=new QwenTts(this);build();initTts();}
    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
    TextView tv(String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(18,10,18,10);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(bg(Color.rgb(100,65,170),30));return b;}
    EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(15);e.setGravity(Gravity.RIGHT);e.setTextColor(Color.DKGRAY);e.setHintTextColor(Color.GRAY);e.setBackground(bg(Color.rgb(247,244,251),24));e.setPadding(18,8,18,8);e.setLayoutParams(new LinearLayout.LayoutParams(-1,60));return e;}
    Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));s.setBackground(bg(Color.rgb(247,244,251),24));s.setLayoutParams(new LinearLayout.LayoutParams(-1,58));return s;}
    void build(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,14,16,24);root.setBackgroundColor(Color.rgb(250,248,253));sc.addView(root);setContentView(sc);TextView h=tv("📖 داستان‌ساز",28,Color.WHITE);h.setGravity(Gravity.CENTER);h.setTypeface(null,1);h.setBackground(bg(Color.rgb(62,39,104),36));root.addView(h,new LinearLayout.LayoutParams(-1,82));TextView sub=tv("داستان، شعر و قصه صوتی با هوش مصنوعی",14,Color.rgb(80,70,95));sub.setGravity(Gravity.CENTER);root.addView(sub);LinearLayout tabs=new LinearLayout(this);Button a=btn("📖 داستان"),p=btn("🎵 شعر"),l=btn("📚 ذخیره‌ها"),q=btn("🔊 Qwen");tabs.addView(a,new LinearLayout.LayoutParams(0,58,1));tabs.addView(p,new LinearLayout.LayoutParams(0,58,1));tabs.addView(l,new LinearLayout.LayoutParams(0,58,1));tabs.addView(q,new LinearLayout.LayoutParams(0,58,1));root.addView(tabs);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content);a.setOnClickListener(v->showStory());p.setOnClickListener(v->showPoem());l.setOnClickListener(v->showLibrary());q.setOnClickListener(v->qwenSettings());showStory();}
    void clear(){content.removeAllViews();} void label(String s){content.addView(tv(s,14,Color.rgb(74,57,91)));}
    void showStory(){clear();label("موضوع داستان");topic=field("مثلاً: پسری که از تاریکی می‌ترسید");content.addView(topic);label("ژانر");genre=spin(new String[]{"ماجراجویی","کودکانه","فانتزی","طنز","رازآلود","علمی‌تخیلی","خانوادگی","احساسی","آموزشی"});content.addView(genre);label("رده سنی");age=spin(new String[]{"کودک ۴ تا ۷ سال","کودک ۸ تا ۱۲ سال","نوجوان","جوان","بزرگسال","همه سنین"});content.addView(age);label("مدت");length=spin(new String[]{"کوتاه ۲ تا ۳ دقیقه","متوسط ۵ تا ۷ دقیقه","بلند ۱۰ تا ۱۵ دقیقه"});content.addView(length);label("پند یا آموزش");lesson=field("مثلاً: شجاعت و اعتمادبه‌نفس");content.addView(lesson);label("نتیجه دلخواه");ending=field("مثلاً: قهرمان بفهمد ترس طبیعی است اما نباید جلوی او را بگیرد");content.addView(ending);label("نام شخصیت");hero=field("آرش، باران، نیما...");content.addView(hero);LinearLayout r=new LinearLayout(this);Button mic=btn("🎙️ گفتن موضوع"),make=btn("✨ ساخت داستان");r.addView(mic,new LinearLayout.LayoutParams(0,62,1));r.addView(make,new LinearLayout.LayoutParams(0,62,1));content.addView(r);status=tv("آماده‌ام...",13,Color.GRAY);status.setGravity(Gravity.CENTER);content.addView(status);result=tv("",17,Color.rgb(45,35,55));content.addView(result);mic.setOnClickListener(v->listen(topic));make.setOnClickListener(v->generate(false));}
    void showPoem(){clear();label("موضوع شعر");topic=field("مادر، باران، دوستی...");content.addView(topic);label("سبک");genre=spin(new String[]{"احساسی","کودکانه","عاشقانه","طنز","حماسی","معنوی","ترانه"});content.addView(genre);label("قالب");age=spin(new String[]{"آزاد","قافیه‌دار","غزل‌گونه","چهارپاره"});content.addView(age);label("واژه ویژه");hero=field("مثلاً: مریم");content.addView(hero);Button make=btn("🎵 شعرم را بساز");content.addView(make);status=tv("آماده‌ام...",13,Color.GRAY);status.setGravity(Gravity.CENTER);content.addView(status);result=tv("",17,Color.rgb(45,35,55));content.addView(result);make.setOnClickListener(v->generate(true));}
    void showLibrary(){clear();label("📚 داستان‌های ذخیره‌شده");String all=getSharedPreferences("stories",0).getString("all","");if(all.isEmpty()){content.addView(tv("هنوز چیزی ذخیره نشده.",16,Color.GRAY));return;}for(String s:all.split("\\n\\n---\\n\\n")){TextView x=tv(s,16,Color.DKGRAY);x.setBackground(bg(Color.WHITE,24));content.addView(x);Button b=btn("🔊 خواندن");content.addView(b);b.setOnClickListener(v->speak(s));}}
    String key(){String k=BuildConfig.GEMINI_API_KEY;return k==null?"":k.trim();}
    void generate(boolean poem){String t=topic.getText().toString().trim();if(t.isEmpty()){toast("موضوع را وارد کن");return;}status.setText("🧠 در حال آفرینش...");String prompt=poem?"یک شعر فارسی تازه و زیبا درباره «"+t+"» بساز. سبک: "+genre.getSelectedItem()+". قالب: "+age.getSelectedItem()+". واژه ویژه: "+hero.getText()+". فقط شعر را بده.":"یک داستان فارسی کاملاً تازه و جذاب بساز. موضوع: "+t+". ژانر: "+genre.getSelectedItem()+". رده سنی: "+age.getSelectedItem()+". مدت: "+length.getSelectedItem()+". پند: "+lesson.getText()+". نتیجه: "+ending.getText()+". شخصیت: "+hero.getText()+". شروع گیرا، شخصیت‌پردازی، اوج و پایان رضایت‌بخش داشته باشد. فقط متن اثر را بده.";String k=key();if(k.isEmpty()){showText(poem?"نمونه شعر آماده است. برای تولید واقعی GEMINI_API_KEY را تنظیم کن.":"نمونه داستان آماده است. برای تولید واقعی GEMINI_API_KEY را تنظیم کن.");return;}io.execute(()->{try{URL u=new URL("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+URLEncoder.encode(k,"UTF-8"));HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setConnectTimeout(20000);c.setReadTimeout(60000);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);JSONObject body=new JSONObject();body.put("contents",new JSONArray().put(new JSONObject().put("parts",new JSONArray().put(new JSONObject().put("text",prompt)))));c.getOutputStream().write(body.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();String raw=read(in);if(code>=400)throw new Exception("Gemini HTTP "+code);String text=new JSONObject(raw).getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts").getJSONObject(0).getString("text");runOnUiThread(()->showText(text.trim()));}catch(Exception e){runOnUiThread(()->{status.setText("⚠️ خطا");toast(e.getMessage());});}});}
    void showText(String s){result.setText(s);status.setText("✨ آماده شد");LinearLayout bar=new LinearLayout(this);Button sp=btn("🔊 خواندن با Qwen"),save=btn("💾 ذخیره");bar.addView(sp,new LinearLayout.LayoutParams(0,62,1));bar.addView(save,new LinearLayout.LayoutParams(0,62,1));content.addView(bar);sp.setOnClickListener(v->speak(s));save.setOnClickListener(v->save(s));}
    void speak(String s){if(qwen.hasKey()){qwen.speak(s,new QwenTts.Callback(){public void success(){status.setText("🔊 Qwen در حال پخش است");}public void failure(String m){status.setText("🔊 صدای گوشی فعال شد");nativeSpeak(s);}});}else{qwenSettings();nativeSpeak(s);}}
    void nativeSpeak(String s){if(tts!=null){tts.stop();tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"story");}}
    void qwenSettings(){final EditText in=new EditText(this);in.setSingleLine(true);in.setHint("sk-...");in.setText(getSharedPreferences("dastansaz_settings",0).getString("qwen_api_key",""));new AlertDialog.Builder(this).setTitle("🔊 Qwen3-TTS").setMessage("کلید Qwen / DashScope را وارد کن. نکته: Qwen3-TTS رسمی فعلاً فارسی را در فهرست زبان‌های پشتیبانی‌شده ندارد؛ اگر متن فارسی رد شود، برنامه خودکار از صدای فارسی گوشی استفاده می‌کند.").setView(in).setPositiveButton("ذخیره",(d,w)->qwen.setKey(in.getText().toString())).setNegativeButton("لغو",null).show();}
    void save(String s){String old=getSharedPreferences("stories",0).getString("all","");getSharedPreferences("stories",0).edit().putString("all",old.isEmpty()?s:old+"\n\n---\n\n"+s).apply();toast("💾 ذخیره شد");}
    void initTts(){tts=new TextToSpeech(this,r->{if(r==TextToSpeech.SUCCESS){int x=tts.setLanguage(new Locale("fa","IR"));if(x==TextToSpeech.LANG_MISSING_DATA||x==TextToSpeech.LANG_NOT_SUPPORTED)tts.setLanguage(new Locale("fa"));tts.setSpeechRate(.9f);}});}
    void listen(EditText target){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("تشخیص گفتار روی گوشی در دسترس نیست");return;}if(recognizer!=null)recognizer.destroy();recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(new android.speech.RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("صدای شما دریافت نشد");}public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty())target.setText(x.get(0));}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);recognizer.startListening(i);status.setText("🎙️ دارم گوش می‌دهم...");}
    String read(InputStream in)throws Exception{if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x);r.close();return s.toString();}
    void toast(String s){Toast.makeText(this,s==null?"خطا":s,Toast.LENGTH_SHORT).show();}
    @Override protected void onDestroy(){if(qwen!=null)qwen.stop();if(tts!=null)tts.shutdown();if(recognizer!=null)recognizer.destroy();io.shutdownNow();super.onDestroy();}
}
