package com.mahdihi69.pouya;

import android.Manifest;
import android.app.Activity;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.speech.*;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    private WebView web;
    private SpeechRecognizer recognizer;
    private TextToSpeech nativeTts;
    private MediaPlayer player;
    private boolean listening=false, conversation=false, ttsReady=false;
    private final ExecutorService net=Executors.newSingleThreadExecutor();
    private static final int MIC=20, PICK=21;

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setAllowFileAccess(true);s.setAllowContentAccess(true);
        web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){injectTools();}});
        web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest r){runOnUiThread(()->r.grant(r.getResources()));}});
        web.addJavascriptInterface(new Bridge(),"PouyaNative");initTts();initSpeech();
        if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);
        web.loadUrl("https://mahdihi69-art.github.io/my-ai-studio/");
    }
    private void initTts(){nativeTts=new TextToSpeech(this,x->{if(x==TextToSpeech.SUCCESS){int r=nativeTts.setLanguage(new Locale("fa","IR"));ttsReady=r!=TextToSpeech.LANG_MISSING_DATA&&r!=TextToSpeech.LANG_NOT_SUPPORTED;nativeTts.setSpeechRate(.9f);}});}
    private void initSpeech(){if(!SpeechRecognizer.isRecognitionAvailable(this))return;try{recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){listening=true;js("updateVoice('🎙️ پویا گوش می‌دهد...');");}public void onBeginningOfSpeech(){js("updateVoice('🗣️ دارم گوش می‌دهم...');");}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){listening=false;js("updateVoice('🧠 دارم فکر می‌کنم...');");}public void onResults(Bundle b){listening=false;ArrayList<String> a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a!=null&&!a.isEmpty())handleVoice(a.get(0));else if(conversation)listen();}public void onError(int e){listening=false;js("updateVoice('⚠️ دوباره بگویید');");if(conversation)new Handler(getMainLooper()).postDelayed(()->listen(),500);}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});}catch(Exception ignored){}}
    private void listen(){if(!conversation||recognizer==null)return;runOnUiThread(()->{try{recognizer.cancel();Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_PREFERENCE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,2);i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);recognizer.startListening(i);}catch(Exception ignored){}});}
    private void handleVoice(String text){text=normalize(text);if(text.isEmpty()){if(conversation)listen();return;}js("showAIMessage("+JSONObject.quote("🎤 "+text)+");");askAI(text);}
    private String normalize(String s){return s.replace('ي','ی').replace('ك','ک').replace('‌',' ').replaceAll("\\s+"," ").trim();}
    private String key(){return BuildConfig.AVALAI_API_KEY==null?"":BuildConfig.AVALAI_API_KEY.trim();}
    private void askAI(String text){final String k=key();if(k.isEmpty()){localFallback(text);return;}net.execute(()->{try{JSONObject body=new JSONObject();body.put("model","gpt-5.6-luna");body.put("temperature",.25);JSONArray m=new JSONArray();m.put(new JSONObject().put("role","system").put("content","تو دستیار صوتی فارسی مدیر مالی پویا هستی. اگر فرمان مالی بود فقط JSON معتبر بده با intent=EXPENSE یا INCOME یا BALANCE یا REPORT یا CHAT و فیلدهای description,amount,reply. مبلغ تومان و عدد صحیح باشد. اگر گفت‌وگوی عادی بود intent=CHAT. reply کوتاه، دوستانه و فارسی باشد."));m.put(new JSONObject().put("role","user").put("content",text));body.put("messages",m);String raw=post("https://api.avalai.ir/v1/chat/completions",k,body.toString());JSONObject root=new JSONObject(raw);String out=root.getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","").trim();out=out.replace("```json","").replace("```","").trim();JSONObject a=new JSONObject(out);applyAi(a);}catch(Exception e){localFallback(text);}});}
    private void localFallback(String text){String t=normalize(text);Long n=findAmount(t);if(n!=null&&(t.contains("خرج")||t.contains("هزینه")||t.contains("پرداخت")||t.contains("خرید"))){String d=t.replaceAll("\\d[\\d,]*"," ").replace("تومان","").trim();js("addTransaction('expense',"+JSONObject.quote(d)+","+n+");showAIMessage('هزینه ثبت شد.');speak('هزینه ثبت شد.');updateVoice('✅ هزینه ثبت شد');");return;}if(t.contains("موجودی")||t.contains("مانده")){js("quickBalance();");return;}answer("متوجه شدم؛ برای ثبت دقیق‌تر مبلغ را هم بگویید.");}
    private Long findAmount(String t){java.util.regex.Matcher m=java.util.regex.Pattern.compile("(\\d[\\d,]*)").matcher(t.replace("٬",""));Long v=null;while(m.find())try{v=Long.parseLong(m.group(1).replace(",",""));}catch(Exception ignored){}if(v!=null){if(t.contains("میلیون"))v*=1000000L;else if(t.contains("هزار"))v*=1000L;}return v;}
    private void applyAi(JSONObject a){String in=a.optString("intent","CHAT"),d=a.optString("description",""),r=a.optString("reply","انجام شد.");long n=a.optLong("amount",0);if("EXPENSE".equals(in)&&n>0)js("addTransaction('expense',"+JSONObject.quote(d)+","+n+");showAIMessage("+JSONObject.quote(r)+");speak("+JSONObject.quote(r)+");updateVoice('✅ هزینه ثبت شد');");else if("INCOME".equals(in)&&n>0)js("addTransaction('income',"+JSONObject.quote(d)+","+n+");showAIMessage("+JSONObject.quote(r)+");speak("+JSONObject.quote(r)+");updateVoice('✅ درآمد ثبت شد');");else if("BALANCE".equals(in))js("quickBalance();");else if("REPORT".equals(in))js("dailyReport();showAIMessage("+JSONObject.quote(r)+");speak("+JSONObject.quote(r)+");");else answer(r);}
    private void answer(String s){js("showAIMessage("+JSONObject.quote(s)+");speak("+JSONObject.quote(s)+");updateVoice('✅ آماده‌ام');");}
    private String post(String u,String key,String data)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(45000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+key);try(OutputStream o=c.getOutputStream()){o.write(data.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String r=read(in);c.disconnect();if(code<200||code>=300)throw new IOException("HTTP "+code);return r;}
    private String read(InputStream in)throws Exception{if(in==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x);return s.toString();}
    private void speak(String text){if(text==null||text.trim().isEmpty())return;final String k=key();net.execute(()->{if(!k.isEmpty())try{JSONObject b=new JSONObject().put("model","gpt-audio-1.5").put("voice","coral").put("input",text).put("response_format","mp3");byte[] audio=downloadBytes("https://api.avalai.ir/v1/audio/speech",k,b.toString());File f=new File(getCacheDir(),"pouya_voice.mp3");try(FileOutputStream o=new FileOutputStream(f)){o.write(audio);}runOnUiThread(()->play(f));return;}catch(Exception ignored){}runOnUiThread(()->nativeSpeak(text));}
    private byte[] downloadBytes(String u,String key,String data)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+key);try(OutputStream o=c.getOutputStream()){o.write(data.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();if(code<200||code>=300)throw new IOException();InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] z=new byte[8192];int n;while((n=in.read(z))!=-1)out.write(z,0,n);in.close();c.disconnect();return out.toByteArray();}
    private void play(File f){try{if(player!=null){player.release();player=null;}player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.setOnCompletionListener(p->{p.release();player=null;if(conversation)listen();});player.setOnErrorListener((p,w,e)->{p.release();player=null;nativeSpeak("");return true;});player.prepare();player.start();}catch(Exception e){nativeSpeak("");}}
    private void nativeSpeak(String s){if(s==null||s.isEmpty()||nativeTts==null||!ttsReady)return;nativeTts.stop();nativeTts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"pouya");}
    private void injectTools(){String css="<style id='pouyaVoiceCss'>#pouyaVoicePanel{position:sticky;top:0;z-index:9999;background:rgba(255,255,255,.96);padding:10px;border-radius:16px;margin:8px 0;box-shadow:0 4px 16px #0002}#pouyaVoicePanel button{border:0;border-radius:12px;padding:10px 13px;margin:3px;font-weight:bold}</style>";String js="javascript:(function(){if(document.getElementById('pouyaVoicePanel'))return;document.head.insertAdjacentHTML('beforeend',"+JSONObject.quote(css)+");var p=document.createElement('div');p.id='pouyaVoicePanel';p.innerHTML='<b>🤖 دستیار پویا</b><br><button onclick=PouyaNative.toggle()>🎤 صحبت با پویا</button><button onclick=PouyaNative.pick()>🖼️ تصویر زمینه</button><span id=voiceState> آماده</span>';var c=document.querySelector('.container')||document.body;c.insertBefore(p,c.firstChild);window.updateVoice=function(x){var e=document.getElementById('voiceState');if(e)e.innerText=' '+x};window.speak=function(x){PouyaNative.speak(String(x))};})();";web.evaluateJavascript(js,null);}
    private void setBackground(Uri uri){try{InputStream in=getContentResolver().openInputStream(uri);Bitmap b=BitmapFactory.decodeStream(in);if(in!=null)in.close();if(b==null)return;int max=1200,w=b.getWidth(),h=b.getHeight();float q=Math.min(1f,(float)max/Math.max(w,h));b=Bitmap.createScaledBitmap(b,Math.max(1,(int)(w*q)),Math.max(1,(int)(h*q)),true);ByteArrayOutputStream out=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,78,out);String data="data:image/jpeg;base64,"+android.util.Base64.encodeToString(out.toByteArray(),android.util.Base64.NO_WRAP);getPreferences(0).edit().putString("bg",data).apply();web.evaluateJavascript("document.body.style.backgroundImage='url("+data+")';document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed';",null);}catch(Exception ignored){}}
    private class Bridge{@JavascriptInterface public void toggle(){runOnUiThread(()->{conversation=!conversation;if(conversation){js("updateVoice('🎙️ دستیار فعال شد؛ صحبت کنید');");listen();}else{if(recognizer!=null)recognizer.cancel();js("updateVoice('⏹️ دستیار خاموش شد');");}});}@JavascriptInterface public void speak(String s){MainActivity.this.speak(s);}@JavascriptInterface public void pick(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PICK);}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null&&d.getData()!=null)setBackground(d.getData());}
    private void js(String x){runOnUiThread(()->web.evaluateJavascript("try{"+x+"}catch(e){}",null));}
    @Override protected void onDestroy(){conversation=false;if(recognizer!=null)recognizer.destroy();if(nativeTts!=null)nativeTts.shutdown();if(player!=null)player.release();net.shutdownNow();super.onDestroy();}
}
