package com.mahdihi69.pouya;

import android.Manifest;
import android.app.Activity;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.media.MediaPlayer;
import android.net.Uri;
import android.os.*;
import android.speech.*;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 WebView web; SpeechRecognizer rec; TextToSpeech tts; MediaPlayer player; boolean voice=false,ttsReady=false; final ExecutorService net=Executors.newSingleThreadExecutor(); static final int MIC=10,PICK=11;
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);web.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){inject();}});web.addJavascriptInterface(new Bridge(),"PouyaNative");initTts();initSpeech();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);web.loadUrl("https://mahdihi69-art.github.io/my-ai-studio/");}
 void initTts(){tts=new TextToSpeech(this,x->{if(x==TextToSpeech.SUCCESS){int r=tts.setLanguage(new Locale("fa","IR"));ttsReady=r!=TextToSpeech.LANG_MISSING_DATA&&r!=TextToSpeech.LANG_NOT_SUPPORTED;tts.setSpeechRate(.9f);}});}
 void initSpeech(){if(!SpeechRecognizer.isRecognitionAvailable(this))return;rec=SpeechRecognizer.createSpeechRecognizer(this);rec.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){js("updateVoice('🎙️ پویا گوش می‌دهد...');");}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){js("updateVoice('🧠 در حال پردازش...');");}public void onResults(Bundle b){ArrayList<String>a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a!=null&&!a.isEmpty())ask(a.get(0));else if(voice)listen();}public void onError(int e){if(voice)new Handler(getMainLooper()).postDelayed(()->listen(),500);}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});}
 void listen(){if(!voice||rec==null)return;try{rec.cancel();Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,2);rec.startListening(i);}catch(Exception ignored){}}
 String key(){return BuildConfig.AVALAI_API_KEY==null?"":BuildConfig.AVALAI_API_KEY.trim();}
 void ask(String text){text=text.replace('ي','ی').replace('ك','ک').trim();if(text.isEmpty()){listen();return;}js("showAIMessage("+JSONObject.quote("🎤 "+text)+");updateVoice('🧠 در حال فکر کردن...');");String k=key();if(k.isEmpty()){answer("دستیار آنلاین تنظیم نشده؛ فرمان شما ثبت نشد.");return;}final String q=text;net.execute(()->{try{JSONObject body=new JSONObject().put("model","gpt-5.6-luna").put("temperature",.2);JSONArray m=new JSONArray();m.put(new JSONObject().put("role","system").put("content","تو دستیار فارسی اپلیکیشن مدیر مالی پویا هستی. فقط JSON معتبر با intent=EXPENSE,INCOME,BALANCE,REPORT,CHAT و description,amount,reply برگردان. مبلغ تومان باشد. reply کوتاه و طبیعی باشد."));m.put(new JSONObject().put("role","user").put("content",q));body.put("messages",m);String r=post("https://api.avalai.ir/v1/chat/completions",k,body.toString());String x=new JSONObject(r).getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","").replace("```json","").replace("```","").trim();apply(new JSONObject(x));}catch(Exception e){answer("فعلاً اتصال دستیار برقرار نشد؛ دوباره بگویید.");}});}
 void apply(JSONObject a){String in=a.optString("intent","CHAT"),d=a.optString("description",""),r=a.optString("reply","انجام شد.");long n=a.optLong("amount",0);if("EXPENSE".equals(in)&&n>0)js("addTransaction('expense',"+JSONObject.quote(d)+","+n+");showAIMessage("+JSONObject.quote(r)+");speak("+JSONObject.quote(r)+");updateVoice('✅ هزینه ثبت شد');");else if("INCOME".equals(in)&&n>0)js("addTransaction('income',"+JSONObject.quote(d)+","+n+");showAIMessage("+JSONObject.quote(r)+");speak("+JSONObject.quote(r)+");updateVoice('✅ درآمد ثبت شد');");else if("BALANCE".equals(in))js("quickBalance();");else if("REPORT".equals(in))js("dailyReport();speak("+JSONObject.quote(r)+");");else answer(r);}
 void answer(String s){js("showAIMessage("+JSONObject.quote(s)+");speak("+JSONObject.quote(s)+");updateVoice('✅ آماده‌ام');");}
 String post(String u,String k,String d)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(45000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+k);try(OutputStream o=c.getOutputStream()){o.write(d.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String r=read(in);c.disconnect();if(code<200||code>=300)throw new IOException();return r;}
 String read(InputStream in)throws Exception{if(in==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x);return s.toString();}
 void speak(String s){if(s==null||s.trim().isEmpty())return;String k=key();if(k.isEmpty()){nativeSpeak(s);return;}net.execute(()->{try{JSONObject b=new JSONObject().put("model","gpt-audio-1.5").put("voice","coral").put("input",s.length()>4096?s.substring(0,4096):s).put("response_format","mp3");byte[] a=bytes("https://api.avalai.ir/v1/audio/speech",k,b.toString());File f=new File(getCacheDir(),"voice.mp3");try(FileOutputStream o=new FileOutputStream(f)){o.write(a);}runOnUiThread(()->play(f));}catch(Exception e){runOnUiThread(()->nativeSpeak(s));}});}
 byte[] bytes(String u,String k,String d)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+k);try(OutputStream o=c.getOutputStream()){o.write(d.getBytes(StandardCharsets.UTF_8));}if(c.getResponseCode()<200||c.getResponseCode()>=300)throw new IOException();InputStream in=c.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] z=new byte[8192];int n;while((n=in.read(z))!=-1)o.write(z,0,n);in.close();c.disconnect();return o.toByteArray();}
 void play(File f){try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.setOnCompletionListener(p->{p.release();player=null;if(voice)listen();});player.prepare();player.start();}catch(Exception e){}}
 void nativeSpeak(String s){if(!ttsReady||tts==null)return;tts.stop();tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"pouya");}
 void inject(){String js="javascript:(function(){if(document.getElementById('pouyaNativePanel'))return;var p=document.createElement('div');p.id='pouyaNativePanel';p.style='position:sticky;top:0;z-index:9999;background:#ffffffee;padding:10px;border-radius:16px;margin:8px;box-shadow:0 3px 15px #0002;text-align:center';p.innerHTML='<b>🤖 دستیار پویا</b> <button onclick=PouyaNative.toggle()>🎤 صحبت</button> <button onclick=PouyaNative.pick()>🖼️ پس‌زمینه</button> <span id=pouyaVoiceState>آماده</span>';var c=document.querySelector('.container')||document.body;c.insertBefore(p,c.firstChild);window.updateVoice=function(x){var e=document.getElementById('pouyaVoiceState');if(e)e.innerText=x};window.speak=function(x){PouyaNative.speak(String(x))};})();";web.evaluateJavascript(js,null);}
 void background(Uri u){try{InputStream in=getContentResolver().openInputStream(u);Bitmap b=BitmapFactory.decodeStream(in);if(in!=null)in.close();if(b==null)return;int m=1200;float q=Math.min(1f,m/(float)Math.max(b.getWidth(),b.getHeight()));b=Bitmap.createScaledBitmap(b,Math.max(1,(int)(b.getWidth()*q)),Math.max(1,(int)(b.getHeight()*q)),true);ByteArrayOutputStream o=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,75,o);String d="data:image/jpeg;base64,"+android.util.Base64.encodeToString(o.toByteArray(),android.util.Base64.NO_WRAP);web.evaluateJavascript("document.body.style.backgroundImage='url("+d+")';document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed';",null);}catch(Exception ignored){}}
 class Bridge{@JavascriptInterface public void toggle(){runOnUiThread(()->{voice=!voice;if(voice){js("updateVoice('🎙️ دستیار فعال شد');");listen();}else{if(rec!=null)rec.cancel();js("updateVoice('⏹️ خاموش شد');");}});}@JavascriptInterface public void speak(String s){MainActivity.this.speak(s);}@JavascriptInterface public void pick(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PICK);}}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null)background(d.getData());}
 void js(String x){runOnUiThread(()->web.evaluateJavascript("try{"+x+"}catch(e){}",null));}
 @Override protected void onDestroy(){voice=false;if(rec!=null)rec.destroy();if(tts!=null)tts.shutdown();if(player!=null)player.release();net.shutdownNow();super.onDestroy();}
}
