plugins { id 'com.android.application' }

def geminiKey = System.getenv("GEMINI_API_KEY") ?: ""
def escapedGeminiKey = geminiKey.replace("\\", "\\\\").replace("\"", "\\\"")

android {
    namespace 'com.mahdihi69.pouya'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mahdihi69.pouya'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2'
        buildConfigField 'String', 'GEMINI_API_KEY', '"' + escapedGeminiKey + '"'
    }

    buildFeatures {
        buildConfig true
    }
}
