plugins { id 'com.android.application' }

android {
    namespace 'com.mahdihi69.builder'
    compileSdk 35
    defaultConfig {
        applicationId "com.mahdihi69.programbuilder"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '2.2.0'
    }
    signingConfigs {
        stableDebug {
            storeFile file("${rootDir}/build-keys/myai-debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
    buildTypes { debug { signingConfig signingConfigs.stableDebug } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
