package com.mahdihi69.story;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.content.*;
import android.content.pm.PackageManager;
import android.view.*;
import android.widget.*;
import android.graphics.drawable.GradientDrawable;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import android.speech.SpeechRecognizer;
import android.speech.RecognizerIntent;
import java.util.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    EditText topic, character, lesson, ending;
    Spinner genre, age, voice, length;
    CheckBox poem;
    TextView output, status, voiceStatus;
    Button generate, speak, stopSpeak, mic, save, share;
    TextToSpeech tts;
    SpeechRecognizer recognizer;
    boolean ttsReady=false, speaking=false;
    final ExecutorService net=Executors.newSingleThreadExecutor();
    final String QWEN_URL="https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions";
    final Random rnd=new Random();

    int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
    EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setSingleLine(false);e.setMinHeight(dp(58));e.setPadding(dp(14),dp(10),dp(14),dp(10));e.setBackground(round(Color.WHITE,dp(14)));return e;}
    GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);g.setStroke(dp(1),Color.rgb(225,226,235));return g;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(7),dp(14),dp(12));c.setBackground(round(Color.WHITE,dp(18)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));c.setLayoutParams(p);return c;}
    TextView iconLabel(String icon,String title,String hint){TextView v=text(icon+"  "+title+"\n"+hint,16,Color.rgb(45,45,65));v.setPadding(dp(5),dp(8),dp(5),dp(8));return v;}
    Button action(String icon,String title){Button b=new Button(this);b.setText(icon+"  "+title);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setMinHeight(dp(50));b.setBackground(round(Color.rgb(91,82,190),dp(15)));return b;}

    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        getWindow().setStatusBarColor(Color.rgb(246,247,251));
        getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(8),dp(14),dp(16));root.setBackgroundColor(Color.rgb(246,247,251));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(0,0,0,dp(20));
        TextView title=text("📖  داستان‌ساز",30,Color.rgb(48,43,95));title.setGravity(Gravity.CENTER);box.addView(title,new LinearLayout.LayoutParams(-1,dp(64)));
        TextView sub=text("✨ داستان، شعر و کتاب صوتی با حالت کم‌مصرف اینترنت",14,Color.rgb(95,94,115));sub.setGravity(Gravity.CENTER);box.addView(sub,new LinearLayout.LayoutParams(-1,dp(32)));
        LinearLayout smart=card();smart.addView(iconLabel("🧠","حالت هوشمند کم‌مصرف","ابتدا Qwen؛ در نبود اینترنت، نویسنده پشتیبان داخل برنامه فعال می‌شود"));box.addView(smart);
        LinearLayout c=card();c.addView(iconLabel("🎯","موضوع داستان","ایده اصلی داستان را بنویسید"));topic=edit("مثلاً سفر یک کودک به شهر ستاره‌ها");c.addView(topic);box.addView(c);
        c=card();c.addView(iconLabel("🧑‍🤝‍🧑","شخصیت‌ها","نام‌ها اختیاری؛ چند شخصیت را با «و» جدا کنید"));character=edit("مثلاً آرش و نیلوفر و ربات کوچولو");c.addView(character);box.addView(c);
        c=card();c.addView(iconLabel("🎭","ژانر و حال‌وهوا","سبک داستان را انتخاب کنید"));genre=new Spinner(this);genre.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"ماجراجویی","آموزشی","طنز","فانتزی","اخلاقی","علمی-تخیلی","احساسی","رازآلود","حماسی","معمایی","محیط‌زیستی","دوستی"}));c.addView(genre);box.addView(c);
        c=card();c.addView(iconLabel("👶","رده سنی","زبان و پیچیدگی داستان بر اساس سن تنظیم می‌شود"));age=new Spinner(this);age.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"کودک ۴ تا ۷ سال","کودک ۸ تا ۱۲ سال","نوجوان","جوان","بزرگسال","خانوادگی"}));c.addView(age);box.addView(c);
        c=card();c.addView(iconLabel("📏","اندازه داستان","حجم متن و زمان شنیدن را انتخاب کنید"));length=new Spinner(this);length.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"کوتاه • حدود ۲ تا ۳ دقیقه","متوسط • حدود ۵ دقیقه","بلند • حدود ۱۰ دقیقه","خیلی بلند • کتابچه‌ای"}));c.addView(length);poem=new CheckBox(this);poem.setText("🎵 همراه شعر یا ترانهٔ کاملاً原创 و مخصوص همین داستان");poem.setTextSize(15);poem.setPadding(0,dp(5),0,0);c.addView(poem);box.addView(c);
        c=card();c.addView(iconLabel("💡","پند یا آموزش","پیام موردنظر را وارد کنید؛ اختیاری"));lesson=edit("مثلاً اهمیت راستگویی و کمک به دیگران");c.addView(lesson);box.addView(c);
        c=card();c.addView(iconLabel("🏁","پایان و نتیجه","نوع پایان را مشخص کنید؛ اختیاری"));ending=edit("مثلاً پایان شاد، غافلگیرکننده و آموزنده");c.addView(ending);box.addView(c);
        c=card();c.addView(iconLabel("🎙️","صدای گوینده","چهار حالت صدای فارسی؛ خواندن روی خود گوشی انجام می‌شود"));voice=new Spinner(this);voice.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"🎙️ گوینده آرام","👨 گوینده جدی","👩 گوینده گرم","🧒 گوینده کودکانه"}));c.addView(voice);voiceStatus=text("در حال آماده‌سازی صدای فارسی گوشی…",13,Color.rgb(100,99,120));voiceStatus.setPadding(dp(4),dp(8),dp(4),0);c.addView(voiceStatus);box.addView(c);
        generate=action("✨","ساخت داستان اختصاصی");LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(58));gp.setMargins(0,dp(9),0,dp(8));box.addView(generate,gp);
        status=text("آماده داستان‌پردازی است",13,Color.rgb(100,99,120));status.setGravity(Gravity.CENTER);box.addView(status,new LinearLayout.LayoutParams(-1,dp(30)));
        LinearLayout outCard=card();TextView outTitle=text("📜  داستان شما",19,Color.rgb(48,43,95));outTitle.setPadding(dp(5),dp(8),dp(5),dp(8));outCard.addView(outTitle);output=text("داستان شما اینجا ساخته می‌شود…",17,Color.rgb(40,40,55));output.setLineSpacing(0,1.45f);output.setTextIsSelectable(true);output.setPadding(dp(10),dp(12),dp(10),dp(18));outCard.addView(output);box.addView(outCard);
        LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER);actions.setPadding(0,dp(4),0,dp(8));speak=action("🔊","خواندن");stopSpeak=action("⏹️","توقف");save=action("💾","ذخیره");share=action("📤","اشتراک");actions.addView(speak,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(52),1);sp.setMargins(dp(5),0,dp(5),0);actions.addView(stopSpeak,sp);box.addView(actions);LinearLayout actions2=new LinearLayout(this);actions2.setPadding(0,0,0,dp(8));mic=action("🎤","فرمان صوتی / گفتن موضوع");actions2.addView(mic,new LinearLayout.LayoutParams(-1,dp(52)));box.addView(actions2);LinearLayout actions3=new LinearLayout(this);actions3.setPadding(0,0,0,dp(8));actions3.addView(save,new LinearLayout.LayoutParams(0,dp(52),1));actions3.addView(share,new LinearLayout.LayoutParams(0,dp(52),1));box.addView(actions3);
        TextView footer=text("🎬 سری‌سازی  •  🎨 داستان اختصاصی  •  🎧 کتاب صوتی  •  📱 تلاش برای کار آفلاین  •  🌐 اینترنت فقط برای کیفیت بالاتر داستان",13,Color.rgb(110,108,130));footer.setGravity(Gravity.CENTER);box.addView(footer,new LinearLayout.LayoutParams(-1,dp(62)));
        scroll.addView(box);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
        initTts();initSpeech();
        generate.setOnClickListener(v->generate());
        voice.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){applyVoice(pos);}});
        speak.setOnClickListener(v->speakStory());stopSpeak.setOnClickListener(v->stopSpeaking());mic.setOnClickListener(v->startVoiceInput());
        save.setOnClickListener(v->{getPreferences(0).edit().putString("last_story",output.getText().toString()).apply();status.setText("💾 داستان در گوشی ذخیره شد");});
        share.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,output.getText().toString());startActivity(Intent.createChooser(i,"اشتراک‌گذاری داستان"));});
    }

    void initTts(){tts=new TextToSpeech(this,s->{if(s==TextToSpeech.SUCCESS){ttsReady=true;int r=tts.isLanguageAvailable(new Locale("fa","IR"));if(r>=TextToSpeech.LANG_AVAILABLE){tts.setLanguage(new Locale("fa","IR"));voiceStatus.setText("✅ صدای فارسی آماده است؛ خواندن داستان می‌تواند بدون اینترنت انجام شود");applyVoice(0);tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){speaking=true;}public void onDone(String id){if(id.startsWith("story_"))runOnUiThread(()->{speaking=false;status.setText("✅ خواندن داستان تمام شد");});}public void onError(String id){runOnUiThread(()->{speaking=false;status.setText("⚠️ خطا در پخش صدا");});}});}else voiceStatus.setText("⚠️ صدای فارسی روی گوشی نصب نیست؛ از تنظیمات موتور گفتار Persian/Farsi را دانلود کنید");}else voiceStatus.setText("⚠️ موتور تبدیل متن به گفتار گوشی آماده نشد");});}
    void applyVoice(int pos){if(!ttsReady)return;float pitch,rate;if(pos==1){pitch=.82f;rate=.88f;}else if(pos==2){pitch=1.08f;rate=.90f;}else if(pos==3){pitch=1.28f;rate=1.02f;}else{pitch=.96f;rate=.86f;}tts.setPitch(pitch);tts.setSpeechRate(rate);try{tts.setLanguage(new Locale("fa","IR"));}catch(Exception ignored){}}
    ArrayList<String> chunks(String s){ArrayList<String> a=new ArrayList<>();String[] paras=s.split("\\n+");StringBuilder cur=new StringBuilder();for(String p:paras){p=p.trim();if(p.isEmpty())continue;if(cur.length()+p.length()+2>1800){if(cur.length()>0){a.add(cur.toString());cur.setLength(0);}if(p.length()>1800){for(int i=0;i<p.length();i+=1600)a.add(p.substring(i,Math.min(i+1600,p.length())));}else cur.append(p);}else{if(cur.length()>0)cur.append("\n\n");cur.append(p);}}if(cur.length()>0)a.add(cur.toString());return a;}
    void speakStory(){String s=output.getText().toString();if(s.isEmpty()||s.startsWith("داستان شما")||s.startsWith("⏳")){status.setText("ابتدا یک داستان بسازید");return;}if(!ttsReady){status.setText("موتور صدای گوشی آماده نیست");return;}applyVoice(voice.getSelectedItemPosition());if(tts.isLanguageAvailable(new Locale("fa","IR"))<TextToSpeech.LANG_AVAILABLE){status.setText("صدای فارسی نصب نیست؛ آن را روی گوشی دانلود کنید");try{startActivity(new Intent(TextToSpeech.Engine.ACTION_INSTALL_TTS_DATA));}catch(Exception ignored){}return;}tts.stop();ArrayList<String> cs=chunks(s);for(int i=0;i<cs.size();i++)tts.speak(cs.get(i),i==0?TextToSpeech.QUEUE_FLUSH:TextToSpeech.QUEUE_ADD,null,"story_"+i);speaking=true;status.setText("🔊 داستان در حال خوانده شدن است…");}
    void stopSpeaking(){if(tts!=null){tts.stop();speaking=false;status.setText("⏹️ خواندن متوقف شد");}}

    void initSpeech(){if(!SpeechRecognizer.isRecognitionAvailable(this)){voiceStatus.append("\n⚠️ فرمان صوتی توسط دستگاه پشتیبانی نمی‌شود");return;}recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(new android.speech.RecognitionListener(){public void onReadyForSpeech(Bundle p){status.setText("🎤 گوش می‌دهم… موضوع یا دستور خود را بگویید");}public void onBeginningOfSpeech(){status.setText("🎤 در حال شنیدن…");}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){status.setText("🧠 در حال تبدیل صدا به متن…");}public void onError(int e){status.setText("⚠️ فرمان صوتی اجرا نشد؛ دوباره روی میکروفون بزنید");}public void onResults(Bundle r){ArrayList<String> x=r.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty()){String q=x.get(0).trim();topic.setText(q);status.setText("✅ موضوع از روی صدا دریافت شد: "+q);generate();}}public void onPartialResults(Bundle r){}public void onEvent(int a,Bundle b){}});}
    void startVoiceInput(){if(recognizer==null){status.setText("⚠️ تشخیص گفتار روی این گوشی در دسترس نیست");return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},77);return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,new Locale("fa","IR").toLanguageTag());i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_PREFERENCE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);i.putExtra("android.speech.extra.PREFER_OFFLINE",true);recognizer.startListening(i);}

    String makePrompt(){String len=length.getSelectedItem().toString();String poemReq=poem.isChecked()?" حتماً یک شعر کوتاه و کاملاً原创 و مخصوص همین داستان در نقطه مناسب داستان قرار بده و شعر را از آثار موجود کپی نکن.":" شعر اضافه نکن.";String[] blueprints={"ساختار سفر و کشف: هدف روشن، سه مانع متفاوت، یک کشف غیرمنتظره و بازگشت با تغییر.","ساختار راز: یک نشانه عجیب، چند سرنخ واقعی، یک سرنخ گمراه‌کننده، افشای منطقی و پایان معنادار.","ساختار نجات: مشکلی فوری، تصمیم دشوار، همکاری چند شخصیت، هزینه یک انتخاب و پیروزی باهوشانه.","ساختار تغییر شخصیت: یک باور اشتباه در آغاز، سه تجربه که آن را به چالش می‌کشد و انتخاب نهایی که رشد شخصیت را نشان می‌دهد.","ساختار جهان شگفت‌انگیز: مکان منحصربه‌فرد، قانون خاص آن دنیا، پیامد شکستن قانون و راه‌حل خلاقانه.","ساختار دوستی و تضاد: دو خواسته متفاوت، سوءتفاهم واقعی، بحران، گفت‌وگوی اثرگذار و آشتی یا تصمیم نهایی.","ساختار معمایی-طنز: مسئله عجیب، اشتباه‌های بامزه اما منطقی، سرنخ‌های پنهان و حل خلاقانه."};String blueprint=blueprints[rnd.nextInt(blueprints.length)];return "یک داستان کاملاً تازه، اختصاصی و غیرتکراری به زبان فارسی بنویس. فقط داستان نهایی را با عنوان برگردان.\nموضوع: "+topic.getText().toString().trim()+"\nشخصیت‌ها: "+character.getText().toString().trim()+"\nژانر: "+genre.getSelectedItem()+"\nرده سنی: "+age.getSelectedItem()+"\nاندازه: "+len+"\nپند/آموزش: "+lesson.getText().toString().trim()+"\nپایان/نتیجه: "+ending.getText().toString().trim()+"\nالگوی روایی تصادفی برای این نوبت: "+blueprint+"\n"+poemReq+"\nقواعد مهم: داستان نباید با عوض کردن نام‌ها شبیه داستان‌های قبلی باشد. مکان، هدف، تعارض، اتفاق اصلی، شخصیت‌های فرعی، نقطه اوج، راه‌حل و پایان را متناسب با موضوع از نو اختراع کن. از عبارت‌های کلیشه‌ای، شروع‌های تکراری و نصیحت مستقیم زیاد پرهیز کن. دیالوگ طبیعی و تصویرسازی شنیداری داشته باش. اگر نام شخصیت خالی است خودت نام‌های متفاوت و مناسب انتخاب کن. برای کتاب صوتی، پاراگراف‌ها کوتاه و خوانا باشند.";}

    void generate(){String t=topic.getText().toString().trim();if(t.isEmpty()){topic.setError("موضوع را وارد کنید");return;}generate.setEnabled(false);status.setText("🪄 در حال خلق یک داستان تازه…");output.setText("⏳ نویسنده هوشمند در حال داستان‌پردازی است…");final String prompt=makePrompt();net.execute(()->{String key=BuildConfig.QWEN_API_KEY==null?"":BuildConfig.QWEN_API_KEY.trim();if(key.isEmpty()){String local=localStory();runOnUiThread(()->{output.setText(local);status.setText("📖 داستان آماده شد • حالت آفلاین");generate.setEnabled(true);});return;}try{String result=callQwen(key,prompt);runOnUiThread(()->{output.setText(result);status.setText("✅ داستان با Qwen ساخته شد");generate.setEnabled(true);});}catch(Exception e){String local=localStory();runOnUiThread(()->{output.setText(local+"\n\n⚠️ سرویس آنلاین در دسترس نبود؛ حالت آفلاین فعال شد.");status.setText("⚠️ اتصال Qwen برقرار نشد؛ حالت آفلاین فعال شد");generate.setEnabled(true);});}});}
    String callQwen(String key,String prompt)throws Exception{Exception last=null;String[] models={"qwen3.8-flash","qwen3.7-flash","qwen3.6-flash"};for(String model:models){HttpURLConnection x=null;try{x=(HttpURLConnection)new URL(QWEN_URL).openConnection();x.setRequestMethod("POST");x.setConnectTimeout(15000);x.setReadTimeout(60000);x.setDoOutput(true);x.setRequestProperty("Authorization","Bearer "+key);x.setRequestProperty("Content-Type","application/json; charset=UTF-8");JSONObject body=new JSONObject();body.put("model",model);JSONArray msgs=new JSONArray();msgs.put(new JSONObject().put("role","system").put("content","تو یک نویسنده حرفه‌ای فارسی برای کتاب صوتی هستی. فقط متن داستان نهایی را با عنوان برگردان و توضیح فنی نده."));msgs.put(new JSONObject().put("role","user").put("content",prompt));body.put("messages",msgs);body.put("temperature",0.95);body.put("max_tokens",6000);try(OutputStream os=x.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=x.getResponseCode();InputStream is=code>=200&&code<300?x.getInputStream():x.getErrorStream();String resp=read(is);if(code>=200&&code<300){JSONObject j=new JSONObject(resp);String r=j.getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","").trim();if(!r.isEmpty())return r;}last=new IOException("HTTP "+code);}catch(Exception e){last=e;}finally{if(x!=null)x.disconnect();}}throw last==null?new IOException("Qwen unavailable"):last;}
    String read(InputStream is)throws Exception{if(is==null)return "";ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=is.read(buf))!=-1)b.write(buf,0,n);return b.toString("UTF-8");}

    String localStory(){String t=topic.getText().toString().trim();String ch=character.getText().toString().trim();if(ch.isEmpty())ch=new String[]{"آرین","نیلوفر","سامان","رها","پارسا"}[rnd.nextInt(5)];String g=genre.getSelectedItem()==null?"ماجراجویی":genre.getSelectedItem().toString();String l=lesson.getText().toString().trim();if(l.isEmpty())l="با فکر کردن، همکاری و شجاعت می‌توان از یک مشکل بزرگ عبور کرد.";String e=ending.getText().toString().trim();if(e.isEmpty())e="پایانی شیرین و امیدوارکننده";String[] places={"ایستگاه قطاری که سال‌ها کسی از آن استفاده نکرده بود","کتابخانه‌ای زیرزمینی با قفسه‌های متحرک","روستایی کنار دریا که شب‌ها فانوس‌هایش خودبه‌خود روشن می‌شدند","شهری کوچک که ساعت میدانش هر روز یک ساعت متفاوت نشان می‌داد","باغی قدیمی پشت یک خانه متروک","آزمایشگاهی کوچک در بالای یک ساختمان بلند"};String[] openings={"همه‌چیز از یک صدای آرام پشت پنجره شروع شد.","صبحی که قرار بود کاملاً عادی باشد، با یک نشانه عجیب تغییر کرد.","هیچ‌کس باور نمی‌کرد یک تصمیم کوچک بتواند چنین ماجرایی بسازد.","آن روز، درست وقتی خورشید از پشت ابر بیرون آمد، اتفاقی افتاد که سال‌ها درباره‌اش حرف زدند.","روی میز فقط یک شیء کوچک بود؛ اما همان شیء مسیر روز را عوض کرد."};String[] twists={"درست وقتی فکر می‌کردند جواب را پیدا کرده‌اند، معلوم شد نشانه اصلی جای دیگری بوده است.","اما مشکل واقعی چیزی نبود که در ابتدا به نظر می‌رسید و آنها مجبور شدند روششان را عوض کنند.","یک اشتباه کوچک، نقشه را به هم زد و در عوض راهی تازه نشانشان داد.","در لحظه اوج، کوچک‌ترین شخصیت گروه نکته‌ای را دید که همه نادیده گرفته بودند."};String[] endings={"در پایان، چیزی که پیدا کردند از خود گنج ارزشمندتر بود: اعتماد به یکدیگر.","آن شب، شهر همان شهر همیشگی بود، اما نگاه آنها به دنیا دیگر مثل قبل نبود.","صبح روز بعد، تصمیم گرفتند این ماجرا را فقط برای خودشان نگه ندارند و آموخته‌شان را با دیگران قسمت کنند."};StringBuilder s=new StringBuilder();s.append("داستان «").append(t).append("»\n\n");s.append(openings[rnd.nextInt(openings.length)]).append("\n\n");s.append(ch).append(" در ").append(places[rnd.nextInt(places.length)]).append(" با مسئله‌ای روبه‌رو شد که به موضوع «").append(t).append("» مربوط بود. فضای ماجرا حال‌وهوای ").append(g).append(" داشت، اما هیچ‌چیز طبق نقشه پیش نمی‌رفت.\n\n");s.append("او اول یک راه ساده را امتحان کرد. جواب نداد. بعد با دقت به اطراف نگاه کرد و از یک شخصیت فرعی کمک خواست. میان گفت‌وگوها، سرنخی پیدا شد که باعث شد هدف اصلی ماجرا روشن‌تر شود.\n\n");s.append(twists[rnd.nextInt(twists.length)]).append(" ").append(ch).append(" چند لحظه سکوت کرد و تصمیم گرفت به جای عجله، مسئله را مرحله‌به‌مرحله حل کند. همین تصمیم مسیر داستان را تغییر داد و باعث شد راه‌حلی پیدا شود که هیچ‌کس از قبل حدس نزده بود.\n\n");s.append(endings[rnd.nextInt(endings.length)]).append("\n\n");if(poem.isChecked())s.append("شعر داستان\n\n").append(poemLocal(t,ch)).append("\n\n");s.append("پیام داستان: ").append(l).append("\n\nنتیجه: ").append(e).append(".");return s.toString();}
    String poemLocal(String t,String ch){String[] a={"در راهی که شب به صبح می‌رسد\nدلِ کوچک ما به نور می‌رسد\nاگر دستِ من در دست تو باشد\nهزار پنجره رو به دور می‌رسد","یک قدم، یک امید، یک نگاه\nمی‌شود چراغی میان سیاه\nاگر با هم از سختی گذر کنیم\nبرای دل‌مان می‌رسد صبحِ ماه","هر جا که پرسش در دل جوانه زد\nراهی تازه از همان‌جا زاده شد\nبا دوستی و با دلِ امیدوار\nقصه‌ی ما دوباره زیبا شد"};return a[rnd.nextInt(a.length)]+"\n\n— شعری تازه برای «"+t+"» و "+ch+".";}

    @Override protected void onDestroy(){if(recognizer!=null)recognizer.destroy();super.onDestroy();if(tts!=null){tts.stop();tts.shutdown();}net.shutdownNow();}
}
