package com.mahdihi69.story;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.media.MediaPlayer;
import android.net.Uri;
import android.os.*;
import android.speech.*;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    EditText topic,chars,lesson,ending; Spinner genre,age,length; CheckBox poem; TextView output,status;
    TextToSpeech nativeTts; SpeechRecognizer rec; MediaPlayer player; boolean ttsReady=false,voiceMode=false;
    final ExecutorService net=Executors.newSingleThreadExecutor(); static final int PICK=31;
    int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(45,45,65));return v;}
    EditText ed(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setPadding(dp(12),dp(8),dp(12),dp(8));e.setMinHeight(dp(55));return e;}
    Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(246,247,251));
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(8),dp(14),dp(14));root.setBackgroundColor(Color.rgb(246,247,251));
        ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);
        TextView title=tx("📖 داستان‌ساز",29);title.setGravity(Gravity.CENTER);box.addView(title,new LinearLayout.LayoutParams(-1,dp(65)));TextView sub=tx("🤖 نویسنده هوشمند + 🎙️ دستیار صوتی فارسی",14);sub.setGravity(Gravity.CENTER);box.addView(sub,new LinearLayout.LayoutParams(-1,dp(38)));
        topic=ed("موضوع داستان را بنویسید یا با صدا بگویید");chars=ed("نام شخصیت‌ها (اختیاری)");lesson=ed("پند یا آموزش (اختیاری)");ending=ed("پایان یا نتیجه دلخواه (اختیاری)");
        add(box,"🎯 موضوع",topic);add(box,"🧑‍🤝‍🧑 شخصیت‌ها",chars);
        genre=new Spinner(this);genre.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"ماجراجویی","فانتزی","آموزشی","طنز","اخلاقی","علمی-تخیلی","احساسی","رازآلود","حماسی","معمایی","دوستی","محیط‌زیستی"}));add(box,"🎭 ژانر",genre);
        age=new Spinner(this);age.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"کودک ۴ تا ۷ سال","کودک ۸ تا ۱۲ سال","نوجوان","جوان","بزرگسال","خانوادگی"}));add(box,"👶 رده سنی",age);
        length=new Spinner(this);length.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"کوتاه","متوسط","بلند","خیلی بلند"}));add(box,"📏 اندازه داستان",length);poem=new CheckBox(this);poem.setText("🎵 شعر تازه و اختصاصی هم اضافه شود");box.addView(poem);add(box,"💡 پند یا آموزش",lesson);add(box,"🏁 پایان",ending);
        LinearLayout voice=new LinearLayout(this);voice.setOrientation(LinearLayout.VERTICAL);voice.setPadding(dp(12),dp(8),dp(12),dp(8));voice.setBackgroundColor(Color.WHITE);voice.addView(tx("🎙️ دستیار صوتی هوشمند",18));voice.addView(tx("صحبت کنید؛ موضوع را می‌فهمد، داستان می‌سازد و پاسخ را با صدای فارسی می‌خواند.",13));Button vb=bt("🎤 شروع گفت‌وگوی صوتی");voice.addView(vb);box.addView(voice);vb.setOnClickListener(v->toggleVoice());
        Button gen=bt("✨ ساخت داستان جدید");box.addView(gen,new LinearLayout.LayoutParams(-1,dp(58)));status=tx("آماده است",13);status.setGravity(Gravity.CENTER);box.addView(status,new LinearLayout.LayoutParams(-1,dp(35)));
        LinearLayout out=new LinearLayout(this);out.setOrientation(LinearLayout.VERTICAL);out.setPadding(dp(12),dp(8),dp(12),dp(10));out.setBackgroundColor(Color.WHITE);out.addView(tx("📜 داستان شما",19));output=tx("اینجا داستان شما ساخته می‌شود…",17);output.setLineSpacing(0,1.45f);output.setTextIsSelectable(true);out.addView(output);box.addView(out);
        LinearLayout row=new LinearLayout(this);Button speak=bt("🔊 خواندن داستان"),stop=bt("⏹️ توقف");row.addView(speak,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(stop,new LinearLayout.LayoutParams(0,dp(54),1));box.addView(row);
        LinearLayout row2=new LinearLayout(this);Button save=bt("💾 ذخیره"),share=bt("📤 اشتراک"),bg=bt("🖼️ تصویر زمینه");row2.addView(save,new LinearLayout.LayoutParams(0,dp(52),1));row2.addView(share,new LinearLayout.LayoutParams(0,dp(52),1));row2.addView(bg,new LinearLayout.LayoutParams(0,dp(52),1));box.addView(row2);
        sc.addView(box);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
        new Handler(getMainLooper()).postDelayed(()->{initTts();initSpeech();},700);
        gen.setOnClickListener(v->generate());speak.setOnClickListener(v->speak(output.getText().toString()));stop.setOnClickListener(v->stopAudio());save.setOnClickListener(v->{getPreferences(0).edit().putString("story",output.getText().toString()).apply();status.setText("💾 ذخیره شد");});share.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,output.getText().toString());startActivity(Intent.createChooser(i,"اشتراک داستان"));});bg.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PICK));
    }
    void add(LinearLayout b,String title,View v){b.addView(tx(title,15));b.addView(v);}
    String qkey(){return BuildConfig.QWEN_API_KEY==null?"":BuildConfig.QWEN_API_KEY.trim();} String akey(){return BuildConfig.AVALAI_API_KEY==null?"":BuildConfig.AVALAI_API_KEY.trim();}
    void generate(){String t=topic.getText().toString().trim();if(t.isEmpty()){status.setText("موضوع را وارد کنید یا صوتی بگویید");return;}String key=qkey();if(key.isEmpty()){status.setText("🪄 ساخت داستان محلی…");localStory(t);return;}status.setText("🧠 در حال ساخت داستان کاملاً تازه…");
        String p="یک داستان کاملاً جدید و غیرتکراری فارسی برای کتاب صوتی بنویس. موضوع: "+t+". شخصیت‌ها: "+chars.getText()+". ژانر: "+genre.getSelectedItem()+". سن: "+age.getSelectedItem()+". طول: "+length.getSelectedItem()+". پند: "+lesson.getText()+". پایان: "+ending.getText()+". "+(poem.isChecked()?"یک شعر کوتاه کاملاً جدید و مرتبط داخل داستان بیاور. ":"")+"داستان باید شروع جذاب، شخصیت‌پردازی، گفت‌وگوی طبیعی، اتفاق غیرمنتظره، نقطه عطف و پایان مشخص داشته باشد و از کلیشه و تکرار پرهیز کند. فقط متن نهایی داستان را برگردان.";
        net.execute(()->{try{JSONObject body=new JSONObject().put("model","qwen3.7-plus").put("temperature",1.12).put("max_tokens",6500);JSONArray m=new JSONArray();m.put(new JSONObject().put("role","system").put("content","فقط فارسی بنویس و خلاق باش."));m.put(new JSONObject().put("role","user").put("content",p));body.put("messages",m);String r=post("https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions",key,body.toString());String s=new JSONObject(r).getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","").trim();runOnUiThread(()->{output.setText(s);status.setText("✅ داستان تازه آماده شد");if(voiceMode)speak(s);});}catch(Exception e){runOnUiThread(()->status.setText("⚠️ ساخت داستان ناموفق بود؛ اتصال را بررسی کنید"));}});}
    void localStory(String t){String n=chars.getText().toString().trim();String l=lesson.getText().toString().trim();String end=ending.getText().toString().trim();String hero=n.isEmpty()?"آرین":n.split("[،, ]")[0];StringBuilder b=new StringBuilder();b.append("📖 ").append(t).append("\n\n");b.append("در شهری آرام، ").append(hero).append(" روزی تصمیم گرفت درباره «").append(t).append("» چیز تازه‌ای کشف کند. او راه افتاد و در مسیر با دوستانش درباره راه‌های مختلف حل مسئله حرف زد. هر بار که مانعی پیش می‌آمد، به‌جای تسلیم شدن، راه دیگری را امتحان می‌کرد.\n\n");b.append("در میانه راه اتفاقی غیرمنتظره افتاد و همه مجبور شدند با دقت بیشتری فکر کنند. ").append(hero).append(" فهمید یک تصمیم کوچک می‌تواند نتیجه بزرگی داشته باشد. دوستانش هم کمک کردند و با همکاری مشکل را حل کردند.\n\n");if(!l.isEmpty())b.append("💡 پند و آموزش: ").append(l).append("\n\n");b.append("🏁 نتیجه: ").append(end.isEmpty()?"کنجکاوی، همکاری و انتخاب درست می‌تواند یک روز معمولی را به خاطره‌ای ماندگار تبدیل کند.":end);output.setText(b.toString());status.setText("✅ داستان آماده شد — حالت آفلاین");if(voiceMode)speak(output.getText().toString());}
    void initTts(){try{nativeTts=new TextToSpeech(this,x->{if(x==TextToSpeech.SUCCESS){int r=nativeTts.setLanguage(new Locale("fa","IR"));ttsReady=r!=TextToSpeech.LANG_MISSING_DATA&&r!=TextToSpeech.LANG_NOT_SUPPORTED;nativeTts.setSpeechRate(.9f);}});}catch(Exception ignored){}}
    void initSpeech(){try{if(!SpeechRecognizer.isRecognitionAvailable(this))return;rec=SpeechRecognizer.createSpeechRecognizer(this);rec.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){status.setText("🎙️ گوش می‌دهم…");}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onResults(Bundle b){ArrayList<String>a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a!=null&&!a.isEmpty())voiceCommand(a.get(0));else if(voiceMode)listen();}public void onError(int e){if(voiceMode)new Handler(getMainLooper()).postDelayed(()->listen(),500);}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});}catch(Exception ignored){}}
    void toggleVoice(){voiceMode=!voiceMode;if(voiceMode){status.setText("🎙️ دستیار صوتی فعال است؛ صحبت کنید");listen();}else{if(rec!=null)rec.cancel();status.setText("⏹️ دستیار صوتی خاموش شد");}}
    void listen(){if(!voiceMode||rec==null)return;try{rec.cancel();Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,2);rec.startListening(i);}catch(Exception ignored){}}
    void voiceCommand(String s){s=s.replace('ي','ی').replace('ك','ک').trim();if(s.isEmpty()){listen();return;}String lower=s;if(lower.contains("داستان")||lower.contains("قصه")||lower.contains("بنویس")||lower.contains("بساز")){String x=s.replace("داستان"," ").replace("قصه"," ").replace("بساز"," ").replace("بنویس"," ").trim();if(x.length()>3)topic.setText(x);generate();}else{topic.setText(s);status.setText("موضوع صوتی دریافت شد؛ برای ساخت داستان دکمه ساخت را بزنید");speak("موضوع را گرفتم. اگر آماده‌ای داستان را می‌سازم.");}if(voiceMode)new Handler(getMainLooper()).postDelayed(()->listen(),900);}
    void speak(String text){if(text==null||text.trim().isEmpty())return;String k=akey();if(!k.isEmpty())net.execute(()->{try{JSONObject b=new JSONObject().put("model","gpt-audio-1.5").put("voice","coral").put("input",text.length()>4096?text.substring(0,4096):text).put("response_format","mp3");byte[] a=bytes("https://api.avalai.ir/v1/audio/speech",k,b.toString());File f=new File(getCacheDir(),"story_voice.mp3");try(FileOutputStream o=new FileOutputStream(f)){o.write(a);}runOnUiThread(()->play(f));return;}catch(Exception ignored){}runOnUiThread(()->nativeSpeak(text));});else nativeSpeak(text);}
    String post(String u,String k,String d)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(90000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+k);try(OutputStream o=c.getOutputStream()){o.write(d.getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String r=read(in);c.disconnect();if(code<200||code>=300)throw new IOException();return r;}
    byte[] bytes(String u,String k,String d)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+k);try(OutputStream o=c.getOutputStream()){o.write(d.getBytes(StandardCharsets.UTF_8));}if(c.getResponseCode()<200||c.getResponseCode()>=300)throw new IOException();InputStream in=c.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] z=new byte[8192];int n;while((n=in.read(z))!=-1)o.write(z,0,n);in.close();c.disconnect();return o.toByteArray();}
    String read(InputStream in)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String z;while((z=r.readLine())!=null)s.append(z);return s.toString();}
    void play(File f){try{stopAudio();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.setOnCompletionListener(p->{p.release();player=null;if(voiceMode)listen();});player.prepare();player.start();}catch(Exception e){nativeSpeak(output.getText().toString());}}
    void nativeSpeak(String s){if(!ttsReady||nativeTts==null)return;nativeTts.stop();nativeTts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"story");}
    void stopAudio(){if(player!=null){player.stop();player.release();player=null;}if(nativeTts!=null)nativeTts.stop();}
    void setBg(Uri u){try{InputStream in=getContentResolver().openInputStream(u);Bitmap b=BitmapFactory.decodeStream(in);if(in!=null)in.close();if(b==null)return;int m=1200;float q=Math.min(1f,m/(float)Math.max(b.getWidth(),b.getHeight()));b=Bitmap.createScaledBitmap(b,Math.max(1,(int)(b.getWidth()*q)),Math.max(1,(int)(b.getHeight()*q)),true);ByteArrayOutputStream o=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,78,o);String d="data:image/jpeg;base64,"+android.util.Base64.encodeToString(o.toByteArray(),android.util.Base64.NO_WRAP);getPreferences(0).edit().putString("bg",d).apply();getWindow().getDecorView().setBackground(new android.graphics.drawable.BitmapDrawable(getResources(),b));}catch(Exception ignored){}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null)setBg(d.getData());}
    @Override protected void onDestroy(){voiceMode=false;if(rec!=null)rec.destroy();if(nativeTts!=null)nativeTts.shutdown();if(player!=null)player.release();net.shutdownNow();super.onDestroy();}
}
